require([
    // Third party libraries
    'underscore',
    'jquery',
    'jquery-behaviors',
    'jquery-form',
    'bootstrap',
    'jScrollPane',
    'jScrollPane.mousewheel',
    'select2',
    'chartist',
    'chartist-plugin-tooltip',
    // Amara modules
    'ajax',
    'dialogs',
    'proxyField',
    'dependentSelect',
    'select',
    'scrollBars',
    'querystring',
    'selectList',
    'videoPage',
    'videoSubtitles',
    'fileUpload',
    'clamp',
    'main',
    'styleGuide',
]);
